#!/usr/bin/env bun
/**
 * Process review files generated by the resolver.
 *
 * After `spoti-bye resolve` runs, flagged tracks land in
 * ~/.spoti-bye/youtube-review-<playlist_id>.json. Edit those files
 * to accept candidates (keep video ID) or mark unavailable (set to null),
 * then run this command to apply changes to the DB.
 *
 * Usage: spoti-bye review
 */

import { Database } from "bun:sqlite";
import { readdirSync, readFileSync, unlinkSync } from "fs";
import { DB_PATH, DEFAULT_DB_DIR } from "./db";
import { dirname } from "node:path";

export async function main() {
  const db = new Database(DB_PATH);
  const reviewDir = dirname(DB_PATH) === DB_PATH ? DEFAULT_DB_DIR : dirname(DB_PATH);

  let files: string[];
  try {
    files = readdirSync(reviewDir).filter(f => f.startsWith("youtube-review-") && f.endsWith(".json"));
  } catch {
    console.log(`No review directory found at ${reviewDir}`);
    return;
  }

  if (files.length === 0) {
    console.log("No review files found. Run `spoti-bye resolve` first.");
    return;
  }

  console.log(`Found ${files.length} review file(s)\n`);

  let accepted = 0;
  let unavailable = 0;
  let skipped = 0;

  const update = db.prepare("UPDATE songs SET youtube_video_id = ? WHERE id = ?");

  for (const file of files) {
    const filePath = `${reviewDir}/${file}`;
    const data = JSON.parse(readFileSync(filePath, "utf-8"));
    let allProcessed = true;

    for (const entry of data) {
      if (entry.best_candidate_video_id && entry.best_candidate_video_id !== "UNAVAILABLE") {
        update.run(entry.best_candidate_video_id, entry.song_id);
        accepted++;
      } else if (entry.best_candidate_video_id === null) {
        update.run("UNAVAILABLE", entry.song_id);
        unavailable++;
      } else {
        skipped++;
        allProcessed = false;
      }
    }

    if (allProcessed) unlinkSync(filePath);
  }

  console.log(`Accepted:           ${accepted}`);
  console.log(`Marked UNAVAILABLE: ${unavailable}`);
  console.log(`Skipped:            ${skipped}`);
  console.log(`\nProcessed ${files.length} review file(s)`);

  db.close();
}

if (import.meta.main) {
  main().catch(err => { console.error("Fatal:", err.message); process.exit(1); });
}
